language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - python ssconf.py
  - python surge_rule_set.py
after_success:
  - cp configFileHere/* gh-pages/
  - cp list/adlist.list gh-pages/adlist.list
  - cp list/gfwlist.list gh-pages/gfwlist.list
  - cp list/whitelist.list gh-pages/whitelist.list

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: gh-pages
  on:
    branch: master
