language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python ssconf.py
after_success:
  - cp configFileHere/* gh-pages/
  - cp list/adlist.txt gh-pages/adlist.list
  - cp list/gfwlist.txt gh-pages/gfwlist.list
  - cp list/whitelist.txt gh-pages/whitelist.list

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: gh-pages
  on:
    branch: master